# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('chinese', '國文'), ('english', '英文'), ('math', '數學'), ('physics', '物理'), ('chemistry', '化學'), ('biology', '生物'), ('earth_science', '地科'), ('geography', '地理'), ('history', '歷史'), ('civil_ethics_education', '公民')], default='math', max_length=25)),
                ('grade', models.CharField(choices=[('10', '高一'), ('5', '小五'), ('7', '國一'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('11', '高二'), ('12', '高三')], default='7', max_length=2)),
                ('day', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], default='1', max_length=1)),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('student_number', models.IntegerField(default=0, max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('classroom', '教室'), ('study_room', '自習室')], default='study_room', max_length=10)),
                ('capacity', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SpaceNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Space')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('10', '高一'), ('5', '小五'), ('7', '國一'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('11', '高二'), ('12', '高三')], default='7', max_length=2)),
                ('school', models.CharField(max_length=100)),
                ('image', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('left', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('contact1_name', models.CharField(default='', max_length=100)),
                ('contact1_relationship', models.CharField(default='', max_length=100)),
                ('contact1_phone', models.CharField(default='', max_length=20)),
                ('contact2_name', models.CharField(default='', max_length=100)),
                ('contact2_relationship', models.CharField(default='', max_length=100)),
                ('contact2_phone', models.CharField(default='', max_length=20)),
                ('contact3_name', models.CharField(default='', max_length=100)),
                ('contact3_relationship', models.CharField(default='', max_length=100)),
                ('contact3_phone', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('grade', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseSigning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sign', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMealsBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0, max_length=10)),
                ('note', models.CharField(default='', max_length=200)),
                ('balance', models.IntegerField(default=0, max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('good', '好'), ('normal', '一般'), ('bad', '差')], default='normal', max_length=6)),
                ('content', models.TextField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(choices=[('chinese', '國文'), ('english', '英文'), ('math', '數學'), ('physics', '物理'), ('chemistry', '化學'), ('biology', '生物'), ('earth_science', '地科'), ('geography', '地理'), ('history', '歷史'), ('civil_ethics_education', '公民')], default='math', max_length=25)),
                ('range', models.CharField(default='', max_length=200)),
                ('need_quiz', models.BooleanField(default=False)),
                ('score', models.CharField(default='', max_length=3)),
                ('finish_quiz', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
                ('note', models.CharField(default='', max_length=200)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(choices=[('chinese', '國文'), ('english', '英文'), ('math', '數學'), ('physics', '物理'), ('chemistry', '化學'), ('biology', '生物'), ('earth_science', '地科'), ('geography', '地理'), ('history', '歷史'), ('civil_ethics_education', '公民')], default='math', max_length=25)),
                ('range', models.CharField(default='', max_length=200)),
                ('finish', models.BooleanField(default=False)),
                ('score', models.CharField(default='', max_length=3)),
                ('note', models.CharField(default='', max_length=200)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSibling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('10', '高一'), ('5', '小五'), ('7', '國一'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('11', '高二'), ('12', '高三')], default='7', max_length=2)),
                ('school', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('note', models.TextField(default='')),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('contact_relationship', models.CharField(default='', max_length=100)),
                ('contact_phone', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], default='1', max_length=1)),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Space')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStudyBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStudySigning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sign', models.BooleanField(default=False)),
                ('finish_homework', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('grade', models.CharField(max_length=100)),
                ('degree_university', models.CharField(max_length=100)),
                ('degree_master', models.CharField(default='', max_length=100)),
                ('degree_doctor', models.CharField(default='', max_length=100)),
                ('resume', models.TextField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TeacherArrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], default='1', max_length=1)),
                ('position', models.CharField(choices=[('normal', '輔導老師'), ('leader', '輔導長')], default='normal', max_length=6)),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Teacher')),
            ],
            options={
                'ordering': ('day', 'position'),
            },
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Space'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram_api.Teacher'),
        ),
    ]
