# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('11', '高二'), ('6', '小六'), ('8', '國二'), ('10', '高一'), ('9', '國三'), ('7', '國一'), ('12', '高三'), ('5', '小五')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('11', '高二'), ('6', '小六'), ('8', '國二'), ('10', '高一'), ('9', '國三'), ('7', '國一'), ('12', '高三'), ('5', '小五')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentcoursebank',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentmealsbank',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentmealsbank',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('11', '高二'), ('6', '小六'), ('8', '國二'), ('10', '高一'), ('9', '國三'), ('7', '國一'), ('12', '高三'), ('5', '小五')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentstudybank',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
