# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0002_auto_20170425_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('5', '小五'), ('11', '高二'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('7', '國一'), ('10', '高一'), ('12', '高三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('5', '小五'), ('11', '高二'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('7', '國一'), ('10', '高一'), ('12', '高三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('5', '小五'), ('11', '高二'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('7', '國一'), ('10', '高一'), ('12', '高三')], default='7', max_length=2),
        ),
    ]
