# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0003_auto_20170425_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='updated_time',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('8', '國二'), ('12', '高三'), ('7', '國一'), ('6', '小六'), ('10', '高一'), ('11', '高二'), ('5', '小五'), ('9', '國三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coursenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spacenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('8', '國二'), ('12', '高三'), ('7', '國一'), ('6', '小六'), ('10', '高一'), ('11', '高二'), ('5', '小五'), ('9', '國三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentcoursebank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentcoursesigning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentmealsbank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('8', '國二'), ('12', '高三'), ('7', '國一'), ('6', '小六'), ('10', '高一'), ('11', '高二'), ('5', '小五'), ('9', '國三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentstudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentstudybank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherarrange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teachernote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
