# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0005_auto_20170426_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('11', '高二'), ('8', '國二'), ('9', '國三'), ('6', '小六'), ('5', '小五'), ('10', '高一'), ('7', '國一'), ('12', '高三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('11', '高二'), ('8', '國二'), ('9', '國三'), ('6', '小六'), ('5', '小五'), ('10', '高一'), ('7', '國一'), ('12', '高三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('11', '高二'), ('8', '國二'), ('9', '國三'), ('6', '小六'), ('5', '小五'), ('10', '高一'), ('7', '國一'), ('12', '高三')], default='7', max_length=2),
        ),
    ]
