# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0006_auto_20170426_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('6', '小六'), ('7', '國一'), ('9', '國三'), ('8', '國二'), ('11', '高二'), ('12', '高三'), ('10', '高一'), ('5', '小五')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('6', '小六'), ('7', '國一'), ('9', '國三'), ('8', '國二'), ('11', '高二'), ('12', '高三'), ('10', '高一'), ('5', '小五')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('6', '小六'), ('7', '國一'), ('9', '國三'), ('8', '國二'), ('11', '高二'), ('12', '高三'), ('10', '高一'), ('5', '小五')], default='7', max_length=2),
        ),
    ]
