# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0007_auto_20170426_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstudysigning',
            name='finish_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='finish_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='finish_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('9', '國三'), ('10', '高一'), ('8', '國二'), ('12', '高三'), ('6', '小六'), ('5', '小五'), ('7', '國一'), ('11', '高二')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('9', '國三'), ('10', '高一'), ('8', '國二'), ('12', '高三'), ('6', '小六'), ('5', '小五'), ('7', '國一'), ('11', '高二')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('9', '國三'), ('10', '高一'), ('8', '國二'), ('12', '高三'), ('6', '小六'), ('5', '小五'), ('7', '國一'), ('11', '高二')], default='7', max_length=2),
        ),
    ]
