# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0010_auto_20170428_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('7', '國一'), ('5', '小五'), ('12', '高三'), ('11', '高二'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('10', '高一')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('7', '國一'), ('5', '小五'), ('12', '高三'), ('11', '高二'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('10', '高一')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('7', '國一'), ('5', '小五'), ('12', '高三'), ('11', '高二'), ('8', '國二'), ('6', '小六'), ('9', '國三'), ('10', '高一')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
