# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0011_auto_20170429_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstudysigning',
            name='create_quiz_at',
            field=models.TimeField(default=datetime.datetime(2017, 5, 2, 22, 16, 58, 224886)),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='finish_homework_at',
            field=models.TimeField(default=datetime.datetime(2017, 5, 2, 22, 16, 58, 224924)),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='have_create_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('10', '高一'), ('12', '高三'), ('11', '高二'), ('7', '國一'), ('5', '小五'), ('6', '小六'), ('8', '國二'), ('9', '國三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('10', '高一'), ('12', '高三'), ('11', '高二'), ('7', '國一'), ('5', '小五'), ('6', '小六'), ('8', '國二'), ('9', '國三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('10', '高一'), ('12', '高三'), ('11', '高二'), ('7', '國一'), ('5', '小五'), ('6', '小六'), ('8', '國二'), ('9', '國三')], default='7', max_length=2),
        ),
    ]
