# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0012_auto_20170502_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursesigning',
            name='leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='finish_plan_at',
            field=models.TimeField(default=datetime.datetime(2017, 5, 3, 15, 7, 2, 888393)),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='finish_quiz_at',
            field=models.TimeField(default=datetime.datetime(2017, 5, 3, 15, 7, 2, 888363)),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='left_at',
            field=models.TimeField(default=datetime.datetime(2017, 5, 3, 15, 7, 2, 888426)),
        ),
        migrations.AddField(
            model_name='studentstudysigning',
            name='sign_at',
            field=models.TimeField(default=datetime.datetime(2017, 5, 3, 15, 7, 2, 888246)),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('7', '國一'), ('6', '小六'), ('8', '國二'), ('10', '高一'), ('5', '小五'), ('11', '高二'), ('9', '國三'), ('12', '高三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('7', '國一'), ('6', '小六'), ('8', '國二'), ('10', '高一'), ('5', '小五'), ('11', '高二'), ('9', '國三'), ('12', '高三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('7', '國一'), ('6', '小六'), ('8', '國二'), ('10', '高一'), ('5', '小五'), ('11', '高二'), ('9', '國三'), ('12', '高三')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='create_quiz_at',
            field=models.TimeField(default=datetime.datetime(2017, 5, 3, 15, 7, 2, 888299)),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='finish_homework_at',
            field=models.TimeField(default=datetime.datetime(2017, 5, 3, 15, 7, 2, 888330)),
        ),
    ]
