# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cram_api', '0013_auto_20170503_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('8', '國二'), ('11', '高二'), ('9', '國三'), ('10', '高一'), ('12', '高三'), ('6', '小六'), ('7', '國一'), ('5', '小五')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('8', '國二'), ('11', '高二'), ('9', '國三'), ('10', '高一'), ('12', '高三'), ('6', '小六'), ('7', '國一'), ('5', '小五')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='grade',
            field=models.CharField(choices=[('8', '國二'), ('11', '高二'), ('9', '國三'), ('10', '高一'), ('12', '高三'), ('6', '小六'), ('7', '國一'), ('5', '小五')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='create_quiz_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='finish_homework_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='finish_plan_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='finish_quiz_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='left_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentstudysigning',
            name='sign_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
